version: '3.9'

services: 
  # MongoDB services
  mongo_db: 
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  # NodeJs API Service
  api:
    build: .
    ports: 
      - 3000:3000
    environment:
      DB_PORT: 27017
      DB_NAME: chattest
      MONGODB_URI: mongodb://db_container:27017
    links:
      - mongo_db
    depends_on:
      - mongo_db
    
volumes:
  mongo_db: {}

